name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Instalar SonarScanner
        run: npm install -g sonarqube-scanner

      - name: Rodar SonarCloud
        run: |
          sonar-scanner \
            -Dsonar.organization=cesargco \
            -Dsonar.projectKey=CesarGCo_teste-devops-ivory \
            -Dsonar.branch.name=main \
            -Dsonar.host.url="https://sonarcloud.io" \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Instalar AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -o awscliv2.zip
          sudo ./aws/install --update


      - name: Configurar Credenciais AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Deploy para a AWS
        run: |
          aws s3 sync ./site s3://meu-site-ivory --delete
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION }} --paths "/*"
